easy_admin:
    design:
        templates:
            layout: 'dashboard.html.twig'

    entities:
        User:
            class: App\Entity\User
            # ...
            edit:
                # change the HTTP method from "POST" to "PUT"
                - { name: 'edit', type: 'method', method: 'PUT' }
                # ...