controllers:
    resource: ../src/Controller/
    type: attribute

app_event:
    path: /event
    methods: [POST]
    controller: App\Controller\EventController::addEvent

edit_event:
    path: /event/edit
    controller: App\Controller\EditEventController::editEvent
    methods: [PUT]

update_event:
    path: '/event/edit/{eventId}'
    controller: 'App\Controller\EditEventController::updateEvent'
    methods: ['PUT']

liste_contacts:
    path: '/user/liste_contacts'
    controller: App\Controller\ListeContactController::index


add_contact:
  path: '/user/{userId}/contact/{contactId}/link'
  controller: App\Controller\AddContactToUserController::addContact
  methods: [POST]

app_profile_user:
    path: '/profile/user'
    controller: App\Controller\ProfileUserController::index
