controllers:
    resource: ../src/Controller/
    type: attribute

app_event:
    path: /event
    methods: [POST]
    controller: App\Controller\EventController::addEvent

edit_event:
    path: /event/edit
    controller: App\Controller\EditEventController::editEvent
    methods: [PUT]

update_event:
    path: '/event/edit/{eventId}'
    controller: 'App\Controller\EditEventController::updateEvent'
    methods: ['PUT']

